# Generated by Django 6.0.5 on 2026-05-31 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_support_phone', models.CharField(blank=True, max_length=40)),
                ('business_phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, max_length=40)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('sales_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('business_hours', models.CharField(blank=True, max_length=120)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'contact information',
                'verbose_name_plural': 'contact information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('inquiry', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_text', models.CharField(default='Nepal ko Swad', max_length=120)),
                ('hero_title', models.CharField(default="One Bite & You Won't Stop Craving", max_length=160)),
                ('hero_highlight', models.CharField(default='Craving', max_length=80)),
                ('hero_subtitle', models.TextField(default='Instant noodles, crunchy snacks, and bulk packs delivered straight to your door. Freshness guaranteed in every bite.')),
                ('primary_button_text', models.CharField(default='Shop Now', max_length=80)),
                ('secondary_button_text', models.CharField(default='Become a Distributor', max_length=80)),
                ('happy_retailers', models.CharField(default='500+', max_length=40)),
                ('product_lines', models.CharField(default='10+', max_length=40)),
                ('districts', models.CharField(default='77', max_length=40)),
            ],
            options={
                'verbose_name': 'homepage content',
                'verbose_name_plural': 'homepage content',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(default='whatsapp', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, help_text='Use /images/... or a full image URL.', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('size_options', models.JSONField(blank=True, default=list, help_text='Example: [{"size": "20g", "price": 10}]')),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('ingredients', models.TextField(blank=True)),
                ('allergy', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='cms.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
