# Generated by Django 6.0.5 on 2026-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', models.CharField(blank=True, default='/images/abouthero.png', max_length=255)),
                ('story_title', models.CharField(blank=True, default='The R&R Story', max_length=255)),
                ('story_paragraphs', models.JSONField(blank=True, default=list)),
                ('mission_title', models.CharField(blank=True, default='Our Mission', max_length=255)),
                ('mission_text', models.TextField(blank=True, default="To become Nepal's most trusted and widely traded snack brand, bringing happiness in every bite.")),
                ('vision_title', models.CharField(blank=True, default='Our Vision', max_length=255)),
                ('vision_text', models.TextField(blank=True, default="To become Nepal's most loved and widely loved snack brand, spreading love and happiness we bring to our customers.")),
                ('quality_title', models.CharField(blank=True, default='Our Commitment To Quality & Safety', max_length=255)),
                ('quality_text', models.TextField(blank=True, default='Our snacks are prepared in a clean, hygienic environment with strict quality checks, ensuring every bite is safe and tasty. From sourcing to packaging, we never compromise.')),
                ('stats', models.JSONField(blank=True, default=list, help_text='Example: [{"value":"50+","label":"Products Manufactured"}]')),
                ('why_choose_title', models.CharField(blank=True, default='Why Choose Riya & Rakshya?', max_length=255)),
                ('why_choose_items', models.JSONField(blank=True, default=list, help_text='Example: [{"title":"Delicious Taste","description":"Authentic Nepal flavours..."}]')),
                ('cta_left_title', models.CharField(blank=True, default='Ready to explore our snacks?', max_length=255)),
                ('cta_left_text', models.TextField(blank=True)),
                ('cta_right_title', models.CharField(blank=True, default='Interested in Bulk Orders or Distribution?', max_length=255)),
                ('cta_right_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'about page content',
                'verbose_name_plural': 'about page content',
            },
        ),
    ]
