# Generated by Django 6.0.5 on 2026-06-08 07:03

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_aboutpagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='cta_left_text',
            field=models.TextField(blank=True, default='Browse our wide collection of freshly crafted snacks, made with quality ingredients and authentic recipes. From crispy bites to rich, flavorful treats, find the perfect treat for every moment.'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='cta_right_text',
            field=models.TextField(blank=True, default="We're always looking for retail partners and distributors across Nepal. Get factory-direct pricing and dedicated support."),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='quality_text',
            field=models.TextField(blank=True, default="Our snacks are prepared in a clean, hygienic environment with strict quality checks, ensuring every bite is safe and tasty. From sourcing to packaging, we never compromise.\n\nOur manufacturing facility follows strict hygiene protocols — our team wears gloves, helmets, and protective gear at all times. We use modern machinery and follow standardized processes to ensure every pack meets our high standards.\n\nWe believe that great taste starts with great ingredients. That's why we source our spices locally and never compromise on the quality of raw materials."),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='stats',
            field=models.JSONField(blank=True, default=cms.models._default_stats, help_text='Example: [{"value":"50+","label":"Products Manufactured"}]'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='story_paragraphs',
            field=models.JSONField(blank=True, default=cms.models._default_story_paragraphs),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='why_choose_items',
            field=models.JSONField(blank=True, default=cms.models._default_why_choose_items, help_text='Example: [{"title":"Delicious Taste","description":"Authentic Nepal flavours..."}]'),
        ),
    ]
