from django.urls import path

from . import admin_views, views

urlpatterns = [
    path("", views.api_root, name="api-root"),
    path("about-content/", views.about_content, name="about-content"),
    path("site-content/", views.site_content, name="site-content"),
    path("categories/", views.categories, name="categories"),
    path("products/", views.products, name="products"),
    path("feedback/", views.feedback, name="feedback"),
    path("contact-info/", views.contact_info, name="contact-info"),
    path("contact-messages/", views.contact_messages, name="contact-messages"),
    path("orders/", views.orders, name="orders"),
    # Admin endpoints
    path("admin/login/", admin_views.admin_login, name="admin-login"),
    path("admin/products/", admin_views.admin_products, name="admin-products"),
    path("admin/products/<int:product_id>/", admin_views.admin_product_detail, name="admin-product-detail"),
    path("admin/categories/", admin_views.admin_categories, name="admin-categories"),
    path("admin/categories/<int:category_id>/", admin_views.admin_category_detail, name="admin-category-detail"),
    path("admin/orders/", admin_views.admin_orders, name="admin-orders"),
    path("admin/orders/<int:order_id>/", admin_views.admin_order_detail, name="admin-order-detail"),
    path("admin/feedback/", admin_views.admin_feedback, name="admin-feedback"),
    path("admin/feedback/<int:feedback_id>/", admin_views.admin_feedback_detail, name="admin-feedback-detail"),
    path("admin/about-content/", admin_views.admin_about_content, name="admin-about-content"),
    path("admin/home-content/", admin_views.admin_home_content, name="admin-home-content"),
    path("admin/contact-info/", admin_views.admin_contact_info, name="admin-contact-info"),
    path("admin/upload/", admin_views.admin_upload, name="admin-upload"),
    path("admin/media/", admin_views.admin_media, name="admin-media"),
    path("admin/setup-status/", admin_views.setup_status, name="setup-status"),
    path("admin/setup/", admin_views.admin_setup, name="admin-setup"),
    path("admin/departments/", admin_views.admin_departments, name="admin-departments"),
    path("admin/departments/<int:department_id>/", admin_views.admin_department_detail, name="admin-department-detail"),
    path("admin/departments/<int:department_id>/members/", admin_views.admin_department_members, name="admin-department-members"),
    path("admin/departments/<int:department_id>/members/<int:member_id>/", admin_views.admin_department_member_detail, name="admin-department-member-detail"),
    path("admin/change-password/", admin_views.change_password, name="change-password"),
    path("admin/forgot-password/", admin_views.forgot_password, name="forgot-password"),
    path("admin/verify-reset-code/", admin_views.verify_reset_code, name="verify-reset-code"),
    path("admin/reset-password/", admin_views.reset_password, name="reset-password"),
    path("admin/send-message/", admin_views.admin_send_message, name="admin-send-message"),
]
